mysql_backups_to_s3: false
tomcat_user: "tomcat7"
tomcat_group: "tomcat7"
openmrs_tomcat_http_port: 8081
openmrs_tomcat_shutdown_port: 8006
openmrs_tomcat_ajp_port: 8011
tomcat_https_port: 8443
openmrs_tomcat_max_filesize: "52428800"
openmrs_tomcat_fsize_threshold: "10485760"
catalina_ops: "-Xms1500M -Xmx1500M"
openmrs_version: "2.1.4"
openmrs_nginx_max_filesize: "50M"
openmrs_install_name: "openmrs"
openmrs_mysql_user: "openmrs"
openmrs_mysql_database: "openmrs"
openmrs_mysql_database_trigger: "openmrs_user_property"
openmrs_mysql_host: "localhost"
openmrs_mysql_app_host: "localhost"
openmrs_mysql_port: 3306
mysql_root_password: "root"
openmrs_mysql_password: "openmrs"
openmrs_dumps_gzipped: true
openmrs_modules: []
openmrs_dump_files: []
ssl_key: "{{ openmrs_site_name }}-key.pem"
ssl_cert: "{{ openmrs_site_name }}-fullchain.pem"
openmrs_system_user: "openmrs"
openmrs_tomcat_instance: "tomcat-openmrs"
openmrs_tomcat_user_home: "/home/{{ openmrs_system_user }}"
openmrs_home_directory: "{{ openmrs_tomcat_user_home }}/{{ openmrs_tomcat_instance }}/.OpenMRS"
openmrs_mysql_connection_url: "jdbc:mysql://{{ openmrs_mysql_host }}:{{ openmrs_mysql_port }}/{{ openmrs_mysql_database }}?autoReconnect=true&sessionVariables=default_storage_engine=InnoDB&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull"
openmrs_install_mysql: yes



# SSL
openmrs_ssl_src_dir: "/etc/letsencrypt/live/{{ openmrs_site_name }}"
openmrs_ssl_cert_file: "fullchain.pem"
openmrs_ssl_key_file: "privkey.pem"
opensrp_certs_from_letsencrypt: true

openmrs_http_site: "{{ openmrs_site_name }}-http"
openmrs_https_site: "{{ openmrs_site_name }}-https"

# Certbot
openmrs_certbot_site_names: ["{{ openmrs_site_name }}"]
openmrs_certbot_mail_address: ""

# NGINX
openmrs_nginx_sites:
  - server:
      name: "{{ openmrs_http_site }}"
      __listen: "80;\n  listen [::]:80;\n"
      server_name: "{{ openmrs_site_name }}"
      return: "301 https://$server_name$request_uri"
      ssl:
        enabled: false

  - server:
      name:  "{{ openmrs_https_site }}"
      __listen: "443;\n  listen [::]:443;\n"
      server_name: "{{ openmrs_site_name }}"
      client_max_body_size: "{{ openmrs_nginx_max_filesize }}"
      ssl:
        enabled: true
        cert: "{{ openmrs_ssl_cert_file }}"
        key:  "{{ openmrs_ssl_key_file }}"
        src_dir: "{{ openmrs_ssl_src_dir }}"
        conf: "{{ openmrs_site_name }}-ssl.conf"
        remote_src: "{{ openmrs_certs_from_letsencrypt }}"
        create_symlink: "{{ openmrs_certs_from_letsencrypt }}"

      location1:
        name: /
        return: "301 https://$host/{{ openmrs_install_name }}"

      location2:
        name: "/{{ openmrs_install_name }}"
        proxy_pass: "http://localhost:{{ openmrs_tomcat_http_port }}/{{ openmrs_install_name }}"
        proxy_read_timeout: "86400s"
        proxy_redirect: "off"
        proxy_next_upstream: "error timeout invalid_header http_502 http_503 http_504"
        proxy_set_header:
          - Host $host
          - X-Real-IP $remote_addr
          - X-Forwarded-For $proxy_add_x_forwarded_for
          - X-Forwarded-Host $server_name
          - X-Forwarded-Proto https

openmrs_nginx_enabled_sites:
  - "{{ openmrs_http_site }}"
  - "{{ openmrs_https_site }}"
