language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - curl -o terraform.zip "https://releases.hashicorp.com/terraform/0.12.1/terraform_0.12.1_linux_amd64.zip"
  - unzip terraform.zip
script:
  - ansible-lint deploy-dhis.yml 
  - ansible-lint deploy-opensrp.yml 
  - ansible-lint deploy-openmrs.yml
  - ./terraform fmt -check=true terraform 
