- hosts: openmrs-app-servers, openmrs-mysql-servers
  gather_facts: False
  pre_tasks:
    - include_tasks: tasks/python2-ubuntu.yml
    - name: Setup Ansible
      setup:
  roles:
    - common

- hosts: openmrs-mysql-servers
  roles:
    - mysql-5.7
  tags:
    - openmrs-mysql

- hosts: openmrs-app-servers
  roles:
    - openmrs
  tags:
    - openmrs-app
