- hosts: opensrp-app-servers, opensrp-couchdb-servers, opensrp-mysql-servers, opensrp-redis-servers, opensrp-activemq-servers, opensrp-postgresql-servers
  gather_facts: False
  pre_tasks:
    - include_tasks: tasks/python3-ubuntu.yml
    - name: Setup Ansible
      setup:
  roles:
    - common

- hosts: opensrp-couchdb-servers
  serial: 1 # Runs playbook one server at at time (to achieve a rolling update)
  max_fail_percentage: 0
  roles:
    - couchdb
  tags:
    - opensrp-couchdb

- hosts: opensrp-mysql-servers
  roles:
    - mysql-5.7
  tags:
    - opensrp-mysql

- hosts: opensrp-redis-servers
  become: true
  become_user: "root"
  roles:
    - onaio.redis
  tags:
    - opensrp-redis

- hosts: opensrp-activemq-servers
  become: true
  become_user: "root"
  roles:
    - activemq
  tags:
    - opensrp-activemq

- hosts: opensrp-postgresql-servers
  become: true
  become_user: "root"
  roles:
    - onaio.postgresql
  tags:
    - opensrp-postgresql
    - opensrp-postgres

- hosts: opensrp-app-servers
  serial: 1 # Runs playbook one server at at time (to achieve a rolling update)
  max_fail_percentage: 0
  roles:
    - opensrp
  tags:
    - opensrp-app
