- hosts: openmrs-app-servers
  gather_facts: False
  pre_tasks:
    - include_tasks: tasks/python2-ubuntu.yml
    - name: Setup Ansible
      setup:
  roles:
    - common
  always_run: true

- hosts: openmrs-app-servers
  roles:
    - openmrs
  tags:
    - openmrs-app
