- src: DavidWittman.redis
  version: 1.2.5

- src: ANXS.postgresql
  version: v1.10.1

- src: https://github.com/onaio/ansible-nginx.git
  name: onaio.nginx
  version: eca5049500549c4e12cb4cb663a8b4f8499ac39b
  scm: git

- src: geerlingguy.java
  version: 1.9.5 

- src: https://github.com/onaio/ansible-redis.git
  name: onaio.redis
  version: 8dfde8fbda8d72b0899f4d38e60f80dd7360ac2b
  scm: git