- src: https://github.com/onaio/postgresql.git
  name: ANXS.postgresql
  version: eecf0b28d8ae833f9118132384447ea19f76c802
  scm: git

- src: https://github.com/onaio/ansible-nginx.git
  name: onaio.nginx
  version: eca5049500549c4e12cb4cb663a8b4f8499ac39b
  scm: git

- src: geerlingguy.java
  version: 1.9.5 

- src: https://github.com/onaio/ansible-redis.git
  name: onaio.redis
  version: 8dfde8fbda8d72b0899f4d38e60f80dd7360ac2b
  scm: git

- src: https://github.com/onaio/ansible-certbot.git
  name: onaio.certbot
  version: a19117aa21a497e9c33e06e52902910f4e26fb1e
  scm: git

- src: geerlingguy.swap
  version: 1.0.0

- src: https://github.com/onaio/ansible-logstash.git
  name: onaio.logstash
  version: 287f0b7ec647bada6df00980df8ff05caed74844
  scm: git
