---
- hosts: reveal_web
  serial: 1  # Runs playbook one server at at time (to achieve a rolling update)
  max_fail_percentage: 0  # Don't continue deploying on other hosts if playbook fails on one
  gather_facts: true
  become: true
  roles:
    - role: onaio.logstash
      tags:
        - logstash
    - role: collectd
      collectd_scripts: ["nginx", "unixsock"]
      tags:
        - collectd
    - role: onaio.monit
      monit_setup_mode: false
      monit_email_admins: "{{ reveal_monit_email_admins }}"
      monit_scripts: "{{ reveal_monit_scripts }}"
      tags:
        - monitoring
        - monit
    - name: "Setup SSL certificates"
      role: certbot
      vars:
        site_name: "{{ reveal_certbot_site_names[0] }}"
        certbot_create_certs: "{{ reveal_certbot_create_certs }}"
        certbot_mail_address: "{{ reveal_certbot_mail_address }}"
        certbot_renew_certs: "{{ reveal_certbot_renew_certs }}"
        certbot_install_cert: "{{ reveal_certbot_install_cert }}"
        certbot_webserver_installed: "nginx"
        certbot_site_names: "{{ reveal_certbot_site_names }}"
        certbot_package: "{{ reveal_certbot_package }}"
        certbot_version: "{{ reveal_certbot_version }}"
      tags:
        - install
        - SSL
        - certbot
      when:
        - reveal_use_certbot == True

    - name: "Setup react"
      role: react
      become: true
      become_user: "root"
      vars:
        react_system_user: "{{ reveal_react_system_user }}"
        react_system_user_home: "{{ reveal_react_system_user_home }}"
        react_codebase_path: "{{ reveal_react_codebase_path }}"
        react_git_url: "{{ reveal_react_git_url }}"
        react_git_version: "{{ reveal_react_git_version }}"
        react_git_key: "{{ reveal_react_git_key }}"
        react_app_settings: "{{ reveal_react_app_settings }}"
        react_build_cmds: "{{ reveal_react_build_cmds }}"
        react_node_version: "{{ reveal_react_node_version | default(omit) }}"
        react_remote_js_build: "{{ reveal_react_remote_js_build }}"
      tags:
        - install
        - react

    - name: "Setup express"
      role: express
      become: true
      become_user: "root"
      vars:
        express_system_user: "{{ reveal_express_system_user }}"
        express_system_user_home: "{{ reveal_express_system_user_home }}"
        express_codebase_path: "{{ reveal_express_codebase_path }}"
        express_git_url: "{{ reveal_express_git_url }}"
        express_git_version: "{{ reveal_express_git_version }}"
        express_git_key: "{{ reveal_express_git_key }}"
        express_app_settings: "{{ reveal_express_app_settings }}"
        express_app_path: "{{ reveal_express_app_path }}"
        express_node_version: 16.x
      tags:
        - install
        - express

    - name: "Setup nginx"
      role: nginx
      become: true
      become_user: "root"
      vars:
        nginx_sites: "{{ reveal_nginx_sites }}"
        nginx_ssl_dir: "{{ reveal_nginx_ssl_dir }}"
        nginx_access_logs: "{{ reveal_nginx_access_logs }}"
        nginx_install_method: "package"
        nginx_enabled_sites: "{{ reveal_nginx_enabled_sites }}"
        nginx_default_enable: false
        monit_protection: "{{ reveal_nginx_monit_protection }}"
        nginx_log_dir: "{{ reveal_nginx_log_path }}"
        nginx_large_client_header_buffers: "{{ reveal_nginx_large_client_header_buffers }}"
        nginx_first_start: "{{ reveal_nginx_first_start }}"
      tags:
        - nginx
        - configure
