- hosts: monitored-servers
  gather_facts: False
  become: yes
  pre_tasks:
    - include_tasks: tasks/python2-ubuntu.yml
    - name: Setup Ansible
      setup:
  roles:
    - role: ssh
      tags:
        - ssh
    - role: server-monitoring
      tags:
        - monitoring
