---
- name: Installing Superset
  hosts: superset
  become: true
  roles:
    - role: onaio.logstash
      tags:
       - logstash

    - role: onaio.redis

    - role: onaio.superset
      tags:
        - superset

    - role: onaio.certbot
      vars:
        certbot_create_certs: "{{ superset_certbot_create_certs }}"
        certbot_site_names:
          - "{{ superset_discover_server_name }}"
        certbot_mail_address: "{{ superset_certbot_mail_address }}"
      when: superset_use_certbot|bool

    - role: onaio.nginx
      vars:
        enable_ssl: true
