---
- name: Copy MySQL configuration files
  become: yes
  become_user: root
  template:
    src: "templates/etc/mysql/conf.d/mysql.cnf.j2"
    dest: "/etc/mysql/conf.d/mysql.cnf"
    owner: "root"
    group: "root"
    mode: 0744

- name: Start the MySQL service
  become: yes
  become_user: root
  service:
    name: mysql
    state: started
    enabled: true

- name: Set MySQL's root user's password
  become: yes
  become_user: root
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
