---
# Required variables:
#  mysql_root_password

- name: Add the MySQL Repository
  become: yes
  become_user: root
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu trusty universe
    state: present

- name: Install MySQL 5.7 Client
  become: yes
  become_user: root
  apt:
    name: "{{ item.name }}={{ item.version }}"
    state: present
    update_cache: yes
  with_items:
    - { name: mysql-client-5.7, version: "{{ mysql_client_version }}" }
    - { name: "{{ mysql_python_package_debian }}", version: "{{ mysql_python_mysqldb_version }}" }
