---
- include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Make sure the CouchDB user exists
  become: yes
  become_user: "root"
  user:
    name: "{{ couchdb_system_user }}"
    group: "{{ couchdb_system_group }}"
    state: present

- name: Copy CouchDB's main config file
  become: yes
  become_user: "root"
  template:
    src: templates/etc/couchdb/local.ini.j2
    dest: /etc/couchdb/local.ini
    owner: "{{ couchdb_system_user }}"
    group: "{{ couchdb_system_group }}"
    mode: 0640

- name: Enable and start CouchDB service
  become: yes
  become_user: "root"
  service:
    name: couchdb
    enabled: true
    state: restarted

- name: Waits for port 5984 of any IP to close active connections, don't start checking for 10 seconds
  wait_for:
    host: 127.0.0.1
    port: 5984
    delay: 10

- name: Check if CouchDB admin user exists
  uri:
    url: "http://127.0.0.1:{{ couchdb_port }}/_config/admins/{{ couchdb_admin_user }}"
    method: GET
    user: "{{ couchdb_admin_user }}"
    password: "{{ couchdb_admin_password }}"
    force_basic_auth: yes
  ignore_errors: true
  register: _couchdb_admin_user_check

- name: Add CouchDB non-existing admin user
  uri:
    url: "http://127.0.0.1:{{ couchdb_port }}/_config/admins/{{ couchdb_admin_user }}"
    method: PUT
    body: "\"{{ couchdb_admin_password }}\""
  retries: 50
  when: _couchdb_admin_user_check.status == 404

- name: Return to user instructions for deleting admin user
  debug:
    msg: |
      Admin user password seems to have changed, or is wrong.
      This role doesn't yet support changing the admin password
  failed_when: true
  when: _couchdb_admin_user_check.status == 401

- name: Create the CouchDB databases
  uri:
    url: "http://127.0.0.1:{{ couchdb_port }}/{{ item }}"
    method: PUT
    user: "{{ couchdb_admin_user }}"
    password: "{{ couchdb_admin_password }}"
    force_basic_auth: yes
    status_code: 200, 201, 412
  with_items: "{{ couchdb_databases }}"
