---
- name: Make sure pip is installed
  when: couchdb_backups_to_s3
  become: true
  become_user: root
  apt:
    name: "python-pip={{ couchdb_backup_pip_version }}"
    state: present

- name: Make sure duplicity is installed
  when: couchdb_backups_to_s3
  become: true
  become_user: root
  apt:
    name: "duplicity={{ couchdb_backup_duplicity_version }}"
    state: present
