---
postgresql_version: "10"
postgresql_cluster_name: "main"
postgresql_cluster_reset: false
postgresql_tablespaces_dirs:
  - "{{ all_psql_table_space_dir }}/core"
  - "{{ all_psql_table_space_dir }}/error"
  - "{{ all_psql_table_space_dir }}/schedule"
  - "{{ all_psql_table_space_dir }}/feed"
  - "{{ all_psql_table_space_dir }}/form"
postgresql_users:
  - name: "{{ all_opensrp_postgres_superuser }}"
    pass: "{{ all_opensrp_postgres_superuser_password }}"
    encrypted: yes
postgresql_databases:
  - name: "{{ all_opensrp_postgresql_database }}"
    owner: "{{ all_opensrp_postgres_superuser }}"
    uuid_ossp: yes
    citext: yes
postgresql_user_privileges:
  - name: "{{ all_opensrp_postgres_superuser }}"
    db: "{{ all_opensrp_postgresql_database }}"
    priv: "ALL"
    role_attr_flags: "SUPERUSER"