tomcat_service_version: "9.0.*"
tomcat_http_port: "8080"
tomcat_ajp_port: "8009"
tomcat_shutdown_port: "8005"
tomcat_max_filesize: "52428800"
tomcat_fsize_threshold: "10485760"
tomcat_user: "tomcat"
tomcat_group: "tomcat"
tomcat_user_home: /opt
tomcat_instance: tomcat
tomcat_catalina_ops: ""
# The number of days to keep Tomcat logs before deleting them
tomcat_logs_max_age_days: 90
# The maximum file size of Tomcat logs before rotating them
tomcat_logs_max_file_size: 500M
# The number of Tomcat log files to maintain
tomcat_logs_archives_to_keep: 7
# logs that will be rotated using logrotate
tomcat_rotated_logs:
  - "{{ tomcat_logs_dir }}/catalina.out"

