---
- name: make sure the import directory is empty
  become: yes
  become_user: "root"
  file:
    path: "{{ import_directory }}"
    state: absent

- name: make sure the import directory is empty
  become: yes
  become_user: "root"
  file:
    path: "{{ import_directory }}"
    state: directory
    mode: 0750
    owner: "{{ gpg_user }}"
    group: "{{ gpg_group }}"

- name: Check gpg keys exist
  local_action: stat path="{{ gpg_private_key }}"
  register: result

- name: copy gpg keys
  copy:
    src: "{{ item.src }}"
    dest: "{{ import_directory }}/{{ item.name }}"
    owner: "{{ gpg_user }}"
    group: "{{ gpg_group }}"
    mode:  0600
  become: yes
  become_user: "{{ gpg_user }}"
  with_items:
    - { name: public.key, src: "{{ gpg_private_key }}" }
    - { name: private.key, src: "{{ gpg_public_key }}" }
    - { name: trust, src: "{{ gpg_trust_file }}" }
  when: result.stat.exists == True

- name: Make sure the GPG config exists
  become: yes
  become_user: "{{ gpg_user }}"
  command: "gpg --list-keys"
  args:
    creates: "{{ gpg_home }}/.gnupg"

- name: import public key
  become: yes
  become_user: "{{ gpg_user }}"
  command: "gpg --trustdb-name {{ gpg_trustdb_file }} --import {{ import_directory }}/public.key"
  args:
    creates: "{{ gpg_home }}/.gnupg/{{ gpg_trustdb_file }}"
  when: gpg_import_public_key

- name: import private key
  become: yes
  become_user: "{{ gpg_user }}"
  command: "gpg --allow-secret-key-import {{ import_directory }}/private.key"
  changed_when: output is defined and output.stdout != ""
  when: gpg_import_public_key

- name: Add trust
  become: yes
  become_user: "{{ gpg_user }}"
  command: "gpg --import-ownertrust {{ import_directory }}/trust"
  changed_when: output is defined and output.stdout != ""
  when: gpg_import_public_key

- name: delete temporary files
  become: yes
  become_user: "root"
  file:
    path: "{{ import_directory }}"
    state: absent
