---
# Required variables:
#  mysql_root_password

- name: Add the MySQL Repository
  become: yes
  become_user: root
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu trusty universe
    state: present

- name: Install MySQL 5.6 Client
  become: yes
  become_user: root
  apt:
    name: "{{ item.name }}={{ item.version }}"
    state: present
    update_cache: yes
  with_items:
    - { name: mysql-client-5.6, version: "{{ mysql_client_version }}" }
    - { name: python-mysqldb, version: "{{ mysql_python_mysqldb_version }}" }

- name: Install MySQL 5.6 Server
  become: yes
  become_user: root
  apt:
    name: "mysql-server-5.6={{ mysql_server_version }}"
    state: present
    update_cache: yes
  when: mysql_install_server