opensrp_git_url: "https://github.com/OpenSRP/opensrp-server.git"
opensrp_resource_sub_dirs:
  - "images"
  - "multimedia"
  - "qr-codes"
opensrp_mysql_port: 3306
opensrp_mysql_host: "localhost"
opensrp_mysql_database: "opensrp"
opensrp_motech_database: "motechquartz"
opensrp_mysql_user: "opensrp"
opensrp_mysql_password: "opensrp"
opensrp_openmrs_url: "https://{{ openmrs_site_name }}/{{ openmrs_install_name }}/"
opensrp_install_name: "opensrp"
opensrp_resource_dir: "/var/lib/OpenSRP"
opensrp_version: "zeir-1.1.2"
opensrp_openmrs_user: "admin"
opensrp_openmrs_password: "admin"
opensrp_dhis_user: "admin"
opensrp_dhis_password: "admin"
opensrp_couchdb_server: "localhost"
opensrp_mysql_app_host: "localhost"
opensrp_couchdb_port: 5984
opensrp_couchdb_user: "root"
opensrp_couchdb_password: "root"
opensrp_rapidpro_token: ""
opensrp_nginx_max_filesize: "50M"
opensrp_local_checkout_path: "/tmp/opensrp"
opensrp_local_package_directory: "/tmp/opensrp-wars"
activemq_version: "5.12"
couchdb_databases:
  - "opensrp"
couchdb_admin_user: "root"
couchdb_admin_password: "root"
couchdb_version: "1.6.0-0ubuntu7"
couchdb_backups_to_s3: false
couchdb_lucene_install_path: "/opt/couchdb-lucene"
couchdb_lucene_support: true
couchdb_lucene_version_name: "v1.1.0"
couchdb_lucene_version_number: "1.1.0"
couchdb_backup_database: "opensrp"
allowed_couchdb_hosts: []
activemq_memory_opts: "-Xms2048M -Xmx2048M"
mysql_backups_to_s3: false
tomcat_user: "tomcat7"
tomcat_group: "tomcat7"
opensrp_tomcat_http_port: 8082
opensrp_tomcat_shutdown_port: 8007
opensrp_tomcat_ajp_port: 8012
tomcat_https_port: 8443
opensrp_tomcat_max_filesize: "52428800"
opensrp_tomcat_fsize_threshold: "10485760"
catalina_ops: "-Xms1500M -Xmx1500M"
ssl_key: "{{ opensrp_site_name }}-key.pem"
ssl_cert: "{{ opensrp_site_name }}-fullchain.pem"
opensrp_system_user: "opensrp"
opensrp_tomcat_instance: "tomcat-opensrp"
opensrp_user_home: "/home/{{ opensrp_system_user }}"
