---
- debug:
    msg:
      - "Open the OpenMRS initial setup page on https://{{ openmrs_site_name }}/{{ openmrs_install_name }}/initialsetup and follow these steps:"
      - ""
      - "On the first page:"
      - "Which language do you prefer? English"
      - ""
      - "On the second page:"
      - "Which type of installation do you want? Advanced"
      - ""
      - "On page labeled 'Step 1 of 5'"
      - "Please specify how to connect to your currently installed database server:"
      - "  Database connection: jdbc:mysql://mariadb.reveal.smartregister.org:3306/@DBNAME@?autoReconnect=true&sessionVariables=default_storage_engine=InnoDB&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull"
      - "Do you currently have an OpenMRS database installed that you would like to connect to? Yes"
      - "  If yes, what is the name of this database? openmrs"
      - ""
      - "On page labeled 'Step 2 of 5'"
      - "Do you need OpenMRS to automatically create the tables for your current database openmrs? Yes"
      - "Do you currently have a database user other than root that has read/write access to the openmrs database? Yes"
      - "  If yes, specify the log in user name and password for that database user:"
      - "    Username: {{ openmrs_mysql_user }}"
      - "    Password: Enter the value in openmrs_mysql_password"
      - ""
      - "On page labeled 'Step 3 of 5'"
      - "Do you want to be able to upload modules from the web interface? No"
      - "Do you want updates to the database to be automatically applied on startup when a new web application is deployed? Yes"
      - ""
      - "On page labeled 'Step 4 of 5'"
      - "Currently the default administrator user/pass is admin:test. Please specify a new password for that user"
      - "  Password: Enter the value in openmrs_admin_password"
      - "  Retype password: Enter the value in openmrs_admin_password"
