---
- name: Create the OpenMRS MySQL Database
  mysql_db:
    login_host: "{{ openmrs_mysql_host }}"
    login_user: "{{ openmrs_mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    name: "{{ openmrs_mysql_database }}"
    state: present

- name: Create the OpenMRS MySQL User
  mysql_user:
    login_host: "{{ openmrs_mysql_host }}"
    login_user: "{{ openmrs_mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    name: "{{ openmrs_mysql_user }}"
    password: "{{ openmrs_mysql_password }}"
    host: "{{ openmrs_mysql_app_host }}"
    priv: "{{ openmrs_mysql_database }}.*:ALL"
    state: present

- name: Copy OpenMRS User Property Trigger .sql to host tmp
  become: yes
  become_user: "root"
  copy:
    src: "tmp/openmrs_user_property_trigger.sql"
    dest: "/tmp/{{ openmrs_mysql_database_trigger }}.sql"
    owner: root
    group: root
    mode: 0700

- name: Import the OpenMRS trigger .sql file
  become: yes
  become_user: "root"
  mysql_db:
    name: "{{ openmrs_mysql_database }}"
    login_user: "{{ openmrs_mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ openmrs_mysql_host }}"
    state: import
    target: "/tmp/{{ openmrs_mysql_database_trigger }}.sql"

- name: Create OpenMRS Config Directory
  become: yes
  become_user: root
  file:
    path: "{{ openmrs_home_directory }}"
    owner: "{{ openmrs_system_user }}"
    group: "{{ tomcat_group }}"
    state: directory
    mode: 0775

- name: Copy the OpenMRS Runtime Template
  become: yes
  become_user: root
  template:
    src: "templates/usr/share/tomcat7/.OpenMRS/openmrs-runtime.properties.j2"
    dest: "{{ openmrs_tomcat_user_home }}/{{ openmrs_tomcat_instance }}/.OpenMRS/openmrs-runtime.properties"
    owner: "{{ openmrs_system_user }}"
    group: "{{ tomcat_group }}"
    mode: 0640

- name: Create a symbolic link of the OpenMRS config directory
  become: yes
  become_user: root
  file:
    src: "{{openmrs_home_directory}}"
    dest: "/var/lib/OpenMRS"
    owner: "{{ openmrs_system_user }}"
    group: "{{ tomcat_group }}"
    state: link
    mode: 0777

- set_fact:
    openmrs_modules: "{{ openmrs_modules_v1 if (openmrs_version < 2) else openmrs_modules_v2 }}"
    template:
      "templates/conditionals/openmrs_version_template.j2"

- include_tasks: modules.yml
  when: openmrs_modules|length > 0

- name: Make sure the OpenMRS directory is absent in Tomcat's app directory
  become: yes
  become_user: root
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ openmrs_tomcat_user_home }}/{{ openmrs_tomcat_instance }}/webapps/{{ openmrs_install_name }}.war"
    - "{{ openmrs_tomcat_user_home }}/{{ openmrs_tomcat_instance }}/webapps/{{ openmrs_install_name }}"

- name: Install the OpenMRS Binary
  become: yes
  become_user: root
  get_url:
    url: "https://netcologne.dl.sourceforge.net/project/openmrs/releases/OpenMRS_Platform_{{ openmrs_version }}/openmrs.war"
    dest: "{{ openmrs_tomcat_user_home }}/{{ openmrs_tomcat_instance }}/webapps/{{ openmrs_install_name }}.war"
    owner: "{{ openmrs_system_user }}"
    group: "{{ tomcat_group }}"

- name: Restart the Tomcat7 Service
  become: yes
  become_user: root
  service:
    name: "{{openmrs_tomcat_instance}}"
    state: restarted
