---
- name: Create the OpenMRS MySQL Database
  mysql_db:
    login_host: "{{ openmrs_mysql_host }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ openmrs_mysql_database }}"
    state: present

- name: Create the OpenMRS MySQL User
  mysql_user:
    login_host: "{{ openmrs_mysql_host }}"
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    name: "{{ openmrs_mysql_user }}"
    password: "{{ openmrs_mysql_password }}"
    host: "{{ openmrs_mysql_app_host }}"
    priv: "{{ openmrs_mysql_database }}.*:ALL"
    state: present

- name: Copy OpenMRS User Property Trigger .sql to host tmp
  become: yes
  become_user: "root"
  copy:
    src: "tmp/openmrs_user_property_trigger.sql"
    dest: "/tmp/{{ openmrs_mysql_database_trigger }}.sql"
    owner: root
    group: root
    mode: 0700

- name: Create OpenMRS Config Directory
  become: yes
  become_user: root
  file:
    path: "/usr/share/tomcat7/.OpenMRS"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    state: directory
    mode: 0755

- name: Copy the OpenMRS Runtime Template
  become: yes
  become_user: root
  template:
    src: "templates/usr/share/tomcat7/.OpenMRS/openmrs-runtime.properties.j2"
    dest: "/usr/share/tomcat7/.OpenMRS/openmrs-runtime.properties"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: 0640

- name: Create a symbolic link of the OpenMRS config directory
  become: yes
  become_user: root
  file:
    src: "/usr/share/tomcat7/.OpenMRS"
    dest: "/var/lib/OpenMRS"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    state: link
    mode: 0777

- include_tasks: modules.yml
  when: openmrs_modules|length > 0

- name: Make sure the OpenMRS directory is absent in Tomcat's app directory
  become: yes
  become_user: root
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/var/lib/tomcat7/webapps/{{ openmrs_install_name }}.war"
    - "/var/lib/tomcat7/webapps/{{ openmrs_install_name }}"

- name: Install the OpenMRS Binary
  become: yes
  become_user: root
  get_url:
    url: "https://netcologne.dl.sourceforge.net/project/openmrs/releases/OpenMRS_Platform_{{ openmrs_version }}/openmrs.war"
    dest: "/var/lib/tomcat7/webapps/{{ openmrs_install_name }}.war"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"

- name: Restart the Tomcat7 Service
  become: yes
  become_user: root
  service:
    name: tomcat7
    state: restarted
