---
# Required variables:
#  openmrs_modules
- name: Clean OpenMRS Modules Directory
  become: yes
  become_user: "root"
  file:
    state: absent
    path: "{{ openmrs_home_directory }}/modules"

- name: Create OpenMRS Modules Directory
  become: yes
  become_user: "root"
  file:
    path: "{{ openmrs_home_directory }}/modules"
    owner: "{{ openmrs_system_user }}"
    group: "{{ openmrs_system_group }}"
    state: directory
    mode: 0755

- name: Copy OpenMRS Modules
  become: yes
  become_user: "root"
  copy:
    src: "files/usr/share/tomcat7/.OpenMRS/modules/{{ item }}.omod"
    dest: "{{ openmrs_home_directory }}/modules/{{ item }}.omod"
    mode: 0644
    owner: "{{ openmrs_system_user }}"
    group: "{{ openmrs_system_group }}"
  with_items: "{{ openmrs_modules }}"

- name: Clean open-web-apps files
  become: yes
  become_user: "root"
  file:
    path: "{{ openmrs_home_directory }}/owa"
    state: absent

- name: Install Unarchive prerequisites
  become: yes
  become_user: "root"
  apt:
   name: "unzip"
   state: present

- name: Unarchive open-web-apps files
  become: yes
  become_user: "root"
  unarchive:
   src: "files/usr/share/tomcat7/.OpenMRS/owa.zip"
   dest: "{{ openmrs_home_directory }}"
   owner: "{{ openmrs_system_user }}"
   group: "{{ openmrs_system_group }}"
