apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opensrp.fullname" . }}
  labels:
    {{- include "opensrp.labels" . | nindent 4 }}
data:
  opensrp.keycloak.json: |
    {{ .Values.keycloak_json | toJson }}
  opensrp.context.xml: |
    {{- include "config.opensrp.context.xml" . | nindent 4 }}
  opensrp.properties: |
    {{- include "config.opensrp.properties" . | nindent 4 }}
  mybatis.properties: |
    {{- include "config.mybatis.deployment.properties" . | nindent 4 }}