apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hapi-fhir.fullname" . }}
  labels:
    {{- include "hapi-fhir.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hapi-fhir.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hapi-fhir.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hapi-fhir.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: hapi-fhir-application-properties
          configMap:
            name: {{ include "hapi-fhir.fullname" . }}
       - name: hapi-fhir-initial-scripts
          configMap:
            name: {{ include "hapi-fhir.fullname" . }}     
      initContainers:
        - name: {{ .Chart.Name }}-initial-scripts
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: hapi-fhir-initial-scripts
              mountPath: /data/initial-scripts/create_database.sh
              subPath: hapi.create_database.sh
          command: ["/data/initial-scripts/create_database.sh"]        
      containers:
        - name: {{ .Chart.Name }}-
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: hapi-fhir-application-properties
              mountPath: /data/hapi-fhir/config/application.yaml
              subPath: hapi.application.yaml
          env:
            - name: SPRING_CONFIG_LOCATION
              value: /data/hapi-fhir/config/application.yaml
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
