---
- name: Create DHIS System Group
  become: yes
  become_user: root
  group:
    name: "{{ dhis_system_group }}"
    state: present

- name: Create DHIS System User
  become: yes
  become_user: root
  user:
    name: "{{ dhis_system_user }}"
    group: "{{ dhis_system_group }}"
    groups: "sudo"
    home: "{{ dhis_user_home }}"
    shell: /bin/bash
    state: present

- name: Create DHIS Config Directory
  become: yes
  become_user: "root"
  file:
    path: "{{ dhis_user_home }}/config"
    owner: "{{ dhis_system_user }}"
    group: "{{ dhis_system_group }}"
    state: directory
    mode: 0644

- name: Copy DHIS Config
  become: yes
  become_user: "root"
  template:
    src: "templates/dhis_user_home/config/dhis.conf.j2"
    dest: "{{ dhis_user_home }}/config/dhis.conf"
    owner: "{{ dhis_system_user }}"
    group: "{{ dhis_system_group }}"
    mode: 0600

- name: Download The DHIS2 War
  become: yes
  become_user: "root"
  get_url:
    url: http://s3-eu-west-1.amazonaws.com/releases.dhis2.org/{{ dhis_version }}/dhis.war
    dest: "{{ dhis_user_home }}/{{ dhis_tomcat_instance }}/webapps/ROOT.war"
    owner: "{{ dhis_system_user }}"
    group: "{{ dhis_system_group }}"
  notify:
    - "restart tomcat7 instance"

- name: Copy DHIS Tomcat setenv Script
  become: yes
  become_user: "root"
  template:
    src: "templates/dhis_user_home/dhis_tomcat_instance/bin/setenv.sh.j2"
    dest: "{{ dhis_user_home }}/{{ dhis_tomcat_instance }}/bin/setenv.sh"
    owner: "{{ dhis_system_user }}"
    group: "{{ dhis_system_group }}"
    mode: 0744
  notify:
    - "restart tomcat7 instance"
