---
dependencies: # noqa 701
- role: geerlingguy.swap
  become: true
  become_user: "root"
  swap_file_size_mb: "{{ opensrp_swap_file_size_mb }}"
  swap_swappiness: "{{ opensrp_swap_swappiness }}"
  when: opensrp_install_swap

- role: tomcat7
  install_tomcat_service: false
  tomcat_system_user: "{{ opensrp_system_user }}"
  tomcat_system_group: "{{ tomcat_group }}"
  tomcat_user_home: "{{ opensrp_user_home }}"
  tomcat_instance: "{{ opensrp_tomcat_instance }}"
  tomcat_working_directory: "{{ tomcat_user_home }}/{{ tomcat_instance }}"
  tomcat_http_port: "{{ opensrp_tomcat_http_port }}"
  tomcat_shutdown_port: "{{ opensrp_tomcat_shutdown_port }}"
  tomcat_max_filesize: "{{ opensrp_tomcat_max_filesize }}"
  tomcat_fsize_threshold: "{{ opensrp_tomcat_fsize_threshold }}"
  tomcat_ajp_port: "{{ opensrp_tomcat_ajp_port }}"
  tags:
    - tomcat7

- role: onaio.certbot
  become: true
  become_user: "root"
  certbot_create_certs: true
  certbot_site_names: "{{ opensrp_certbot_site_names }}"
  certbot_mail_address: "{{ opensrp_certbot_mail_address }}"
  when: opensrp_certs_from_letsencrypt
  tags:
    - certbot

- role: onaio.nginx
  site_name: "{{ opensrp_site_name }}"
  site_file: "roles/opensrp/templates/etc/nginx/sites-enabled/opensrp_site_name.j2"
  nginx_install_method: "package"
  nginx_sites: "{{ opensrp_nginx_sites }}"
  nginx_enabled_sites: "{{ opensrp_nginx_enabled_sites }}"
  nginx_disabled_sites: "{{ opensrp_nginx_disabled_sites }}"
  nginx_ssl_dir: "{{ nginx_dir }}/ssl/{{ site.server.server_name }}"
  nginx_server_names_hash_bucket_size: "{{ opensrp_nginx_server_names_hash_bucket_size }}"
  nginx_log_dir: "{{ opensrp_nginx_log_dir }}"
  nginx_access_logs: "{{ opensrp_nginx_access_logs }}"
  become: true
  become_user: "root"
  tags:
    - nginx

- role: collectd
  collectd_deployed_app_name: "opensrp"
  collectd_deployed_app_version: "{{ opensrp_version }}"
  become: True
  tags:
    - collectd

- role: geerlingguy.java
  java_packages: "{{ opensrp_java_packages }}"
  become: true
  become_user: "root"
  tags:
    - java

- role: onaio.logstash
  become: true
  become_user: "root"
  logstash_plugins: "{{ opensrp_logstash_plugins }}"
  logstash_custom_outputs: "{{ opensrp_logstash_custom_outputs }}"
  logstash_custom_inputs: "{{ opensrp_logstash_custom_inputs }}"
  logstash_system_groups: ["adm"]
  config_logstash: true
  logstash_install_java: false
  logstash_input_config_suffix: "{{ opensrp_logstash_input_config_suffix }}"
  clear_logstash_config: "{{ opensrp_clear_logstash_config }}"
  when: opensrp_install_logstash
  tags:
   - logstash
