---
dependencies:
- role: onaio.redis
  become: true
  become_user: "root"
  redis_bind: 127.0.0.1
  redis_version: "{{ opensrp_redis_version }}"
  redis_password: "{{ opensrp_redis_password }}"
  tags:
   - opensrp-redis

- role: tomcat7
  install_tomcat_service: false
  tomcat_system_user: "{{ opensrp_system_user }}"
  tomcat_system_group: "{{ tomcat_group }}"
  tomcat_user_home: "{{ opensrp_user_home }}"
  tomcat_instance: "{{ opensrp_tomcat_instance }}"
  tomcat_Working_directory: "{{ tomcat_user_home }}/{{ tomcat_instance }}"
  tomcat_http_port: "{{ opensrp_tomcat_http_port }}"
  tomcat_shutdown_port: "{{ opensrp_tomcat_shutdown_port }}"
  tomcat_max_filesize: "{{ opensrp_tomcat_max_filesize }}"
  tomcat_fsize_threshold: "{{ opensrp_tomcat_fsize_threshold }}"
  tomcat_ajp_port: "{{ opensrp_tomcat_ajp_port }}"
  tags:
    - tomcat7

- role: activemq
  become: yes
  tags:
    - activemq

- role: onaio.certbot
  become: true
  become_user: "root"
  certbot_create_certs: true
  certbot_site_names: "{{ opensrp_certbot_site_names }}"
  certbot_mail_address: "{{ opensrp_certbot_mail_address }}"
  when: opensrp_certs_from_letsencrypt
  tags:
    - certbot

- role: onaio.nginx
  site_name: "{{ opensrp_site_name }}"
  site_file: "roles/opensrp/templates/etc/nginx/sites-enabled/opensrp_site_name.j2"
  nginx_install_method: "package"
  nginx_sites: "{{ opensrp_nginx_sites }}"
  nginx_enabled_sites: "{{ opensrp_nginx_enabled_sites }}"
  nginx_ssl_dir: "{{ nginx_dir }}/ssl/{{ site.server.server_name }}"
  become: true
  become_user: "root"
  tags:
    - nginx

- role: collectd
  collectd_deployed_app_name: "opensrp"
  collectd_deployed_app_version: "{{ opensrp_version }}"
  become: True
  tags:
    - collectd
    -
- role: oracle-java8
  tags:
   - oracle-java8

- role: postgresql-configuration
  when: opensrp_install_postgres
  tags:
  - psql-table-space
