---
dependencies:
- role: collectd
  collectd_deployed_app_name: "postgresql"
  collectd_deployed_app_version: "-"
  become: True

- role: ANXS.postgresql
  become: true
  become_user: "root"
  postgresql_version: "{{ pg_version }}"
  postgresql_admin_user: "{{ opensrp_psql_admin_user }}"
  postgresql_default_auth_method: "trust"
  postgresql_cluster_name: "main"
  postgresql_cluster_reset: false
  postgresql_users:
  - name: "{{ opensrp_postgresql_user }}"
    pass: "{{ opensrp_postgresql_password }}"
    encrypted: yes
  postgresql_databases:
  - name: "{{ opensrp_postgresql_database }}"
    owner: "{{ opensrp_postgresql_user }}"
    uuid_ossp: yes
    citext: yes
  postgresql_user_privileges:
  - name: "{{ opensrp_postgresql_user }}"
    db: "{{ opensrp_postgresql_database }}"
    priv: "ALL"
    role_attr_flags: "SUPERUSER"


