---
dependencies:
- role: postgresql
  tags:
    - postgresql

- role: oracle-java8
  tags:
    - oracle-java8

- role: tomcat7
  install_tomcat_service: false
  tomcat_system_user: "{{ dhis_system_user }}"
  tomcat_system_group: "{{ tomcat_group }}"
  tomcat_user_home: "{{ dhis_user_home }}"
  tomcat_instance: "{{ dhis_tomcat_instance }}"
  tomcat_Working_directory: "{{ tomcat_user_home }}/{{ tomcat_instance }}"
  tomcat_http_port: "{{ dhis_tomcat_http_port }}"
  tomcat_shutdown_port: "{{ dhis_tomcat_shutdown_port }}"
  tomcat_max_filesize: "{{ dhis_tomcat_max_filesize }}"
  tomcat_fsize_threshold: "{{ dhis_tomcat_fsize_threshold }}"
  tomcat_ajp_port: "{{ dhis_tomcat_ajp_port }}"
  tags:
    - tomcat7

- role: nginx
  site_file: "roles/dhis2/templates/etc/nginx/sites-enabled/site_name.j2"
  site_name: "{{ dhis_site_name }}"
  certs_from_letsencrypt: "{{ dhis_certs_from_letsencrypt }}"
  tags:
    - nginx

- role: collectd
  collectd_deployed_app_name: "dhis2"
  collectd_deployed_app_version: "{{ dhis_version }}"
  become: True
  tags:
    - collectd
