---
dependencies: # noqa 701
- role: geerlingguy.swap
  become: true
  become_user: "root"
  swap_file_size_mb: "{{ dhis_swap_file_size_mb }}"
  swap_swappiness: "{{ dhis_swap_swappiness }}"
  when: dhis_install_swap

- role: geerlingguy.java
  java_packages: "{{ dhis_java_packages }}"
  become: true
  become_user: "root"
  tags:
    - java

- role: tomcat7
  install_tomcat_service: false
  tomcat_system_user: "{{ dhis_system_user }}"
  tomcat_system_group: "{{ dhis_system_group }}"
  tomcat_user_home: "{{ dhis_user_home }}"
  tomcat_instance: "{{ dhis_tomcat_instance }}"
  tomcat_working_directory: "{{ tomcat_user_home }}/{{ tomcat_instance }}"
  tomcat_http_port: "{{ dhis_tomcat_http_port }}"
  tomcat_shutdown_port: "{{ dhis_tomcat_shutdown_port }}"
  tomcat_max_filesize: "{{ dhis_tomcat_max_filesize }}"
  tomcat_fsize_threshold: "{{ dhis_tomcat_fsize_threshold }}"
  tomcat_ajp_port: "{{ dhis_tomcat_ajp_port }}"
  tomcat_https_port: "{{ dhis_tomcat_https_port }}"
  catalina_ops: "{{ dhis_java_ops }}"
  tags:
    - tomcat7

- role: onaio.certbot
  certbot_create_certs: "{{ dhis_certbot_create_certs }}"
  certbot_site_names: "{{ dhis_certbot_site_names }}"
  certbot_mail_address: "{{ dhis_certbot_mail_address }}"
  become: true
  become_user: "root"
  when: dhis_certs_from_letsencrypt
  tags:
    - certbot

- role: onaio.nginx
  nginx_install_method: "package"
  nginx_sites: "{{ dhis_nginx_sites }}"
  nginx_enabled_sites: "{{ dhis_nginx_enabled_sites }}"
  nginx_ssl_dir: "{{ nginx_dir }}/ssl/{{ site.server.server_name }}"
  nginx_log_dir: "{{ dhis_nginx_log_dir }}"
  become: true
  become_user: "root"
  tags:
    - nginx

- role: collectd
  collectd_deployed_app_name: "dhis2"
  collectd_deployed_app_version: "{{ dhis_version }}"
  become: True
  tags:
    - collectd

- role: onaio.logstash
  become: true
  become_user: "root"
  clear_logstash_config: true
  logstash_plugins: "{{ dhis_logstash_plugins }}"
  logstash_custom_outputs: "{{ dhis_logstash_custom_outputs }}"
  logstash_custom_inputs: "{{ dhis_logstash_custom_inputs }}"
  logstash_system_groups: ["adm"]
  config_logstash: true
  logstash_install_java: false
  when: dhis_install_logstash
  tags:
   - logstash
