---
- name: Copy the logrotate configuration
  become: true
  become_user: "root"
  template:
    src: "etc/logrotate.d/tomcat_instance.j2"
    dest: "{{ tomcat_logrotate_conf_dest }}"
    owner: root
    group: root
    mode: 0644
