---
# Required variables:
#  install_tomcat_service
- include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- block:
  - name: Include tomcat-user variables
    include_vars: tomcat_user.yml

  - name: Install tomcat-user
    include_tasks: tomcat_user.yml

  - name: Configure the tomcat-user instance
    include_tasks: tomcat_user_instance.yml
  when: not install_tomcat_service

- block:
  - name: Include the Tomcat service variables
    include_vars: tomcat_service.yml

  - name: Install the Tomcat service
    include_tasks: tomcat_service.yml
  when: install_tomcat_service

- name: Configure Logrotate
  include_tasks: logrotate.yml
