---
- name: Copy Tomcat7 env File
  become: yes
  become_user: "root"
  template:
    src: "templates/usr/share/tomcat7/bin/setenv.sh.j2"
    dest: "/usr/share/tomcat7/bin/setenv.sh"
    owner: "root"
    group: "root"
    mode: 0775

- name: Start & Enable the Tomcat7 Service
  become: yes
  become_user: root
  service:
    name: tomcat7
    state: started
    enabled: true

- name: Update Owner Permission For Shared Tomcat Folder
  become: yes
  become_user: root
  file:
    path: "/usr/share/tomcat7"
    state: directory
    recurse: yes
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
