---
- name: Ensure checkout directory is empty
  file:
    state: absent
    path: "{{ opensrp_local_checkout_path }}"
  delegate_to: 127.0.0.1

- name: Checking out codebase
  git:
    repo: "{{ opensrp_git_url }}"
    dest: "{{ opensrp_local_checkout_path }}"
    version: "{{ opensrp_version }}"
    recursive: yes
  delegate_to: 127.0.0.1

- name: Copy the OpenSRP man config files
  template:
    src: "templates/opensrp_local_checkout_path/opensrp_config_path/{{ item }}.properties.j2"
    dest: "{{ opensrp_local_checkout_path }}/{{ opensrp_config_path }}/{{ item }}.properties"
  delegate_to: 127.0.0.1
  with_items:
    - "opensrp"
    - "couchdb"
    - "activemq"

- name: Copy the OpenSRP resource config file
  template:
    src: "templates/opensrp_local_checkout_path/opensrp_resources_path/{{ item }}.properties.j2"
    dest: "{{ opensrp_local_checkout_path }}/{{ opensrp_resources_path }}/{{ item }}.properties"
  delegate_to: 127.0.0.1
  with_items:
    - "quartz"

- name: Copy the OpenSRP oauth clients config file
  template:
    src: "templates/opensrp_local_checkout_path/opensrp_resources_path/spring/{{ item }}.xml.j2"
    dest: "{{ opensrp_local_checkout_path }}/{{ opensrp_resources_path }}/spring/{{ item }}.xml"
  delegate_to: 127.0.0.1
  with_items:
    - "oauth_clients"

- name: Replace OpenSRP Context configs
  when: opensrp_psql_as_primary_database
  template:
    src: "templates/opensrp_local_checkout_path/opensrp_meta_inf_path/{{ item }}.xml.j2"
    dest: "{{ opensrp_local_checkout_path }}/{{ opensrp_meta_inf_path }}/{{ item }}.xml"
  delegate_to: 127.0.0.1
  with_items:
  - "context"

- name: Replace OpenSRP Keycloak configs
  when: opensrp_keycloak_realm is defined
  template:
    src: "templates/opensrp_local_checkout_path/opensrp_web_inf_path/keycloak.json.j2"
    dest: "{{ opensrp_local_checkout_path }}/{{ opensrp_web_inf_path }}/keycloak.json"
  delegate_to: 127.0.0.1


- name: Add OpenSRP version and build timestamp
  replace:
    path: "{{ opensrp_local_checkout_path }}/{{ opensrp_index_html_path }}"
    after: '</form>'
    before: '</body>'
    regexp: '^(.+)$'
    replace: "<div style='position:fixed;bottom: 0;right: 20px;font-style: italic;color: gray;'>\
     {{ opensrp_version }} built on {{ ansible_date_time.iso8601_micro }} </div>"
  delegate_to: 127.0.0.1

- name: Compile the OpenSRP WAR # noqa 301
  environment:
    JAVA_HOME: "{{ opensrp_compile_java_home }}"
  shell: "cd {{ opensrp_local_checkout_path }} && mvn package -Dmaven.test.skip=true -P {{ opensrp_maven_package_profiles | join(',') }}"
  delegate_to: 127.0.0.1

- name: Make sure the WAR directory exists
  file:
    path: "{{ opensrp_local_package_directory }}"
    state: directory
  delegate_to: 127.0.0.1

- name: Copy the compiled WAR
  copy:
    src: "{{ opensrp_local_checkout_path }}/{{ opensrp_local_war_path }}"
    dest: "{{ opensrp_local_package_directory }}/{{ opensrp_version }}.war"
  delegate_to: 127.0.0.1
