---
- name: Check if OpenSRP already packaged
  stat: "path={{ opensrp_local_package_directory }}/{{ opensrp_version }}.war"
  register: opensrp_package
  delegate_to: 127.0.0.1

- include_tasks: compile.yml

- include_tasks: mysql.yml
  when: opensrp_mysql_database is defined

- name: Create OpenSRP resource directory
  become: yes
  become_user: root
  file:
    path: "{{ opensrp_resource_dir }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    state: directory
    mode: 0755

- name: Create OpenSRP sub-directories
  become: yes
  become_user: root
  file:
    path: "{{ opensrp_resource_dir }}/{{ item }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    state: directory
    mode: 0755
  with_items: "{{ opensrp_resource_sub_dirs }}"

- name: Make sure the OpenSRP directory is absent in Tomcat's app directory
  become: yes
  become_user: root
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/var/lib/tomcat7/webapps/{{ opensrp_install_name }}.war"
    - "/var/lib/tomcat7/webapps/{{ opensrp_install_name }}"

- name: Copy the OpenSRP package
  become: yes
  become_user: root
  copy:
    src: "{{ opensrp_local_package_directory }}/{{ opensrp_version }}.war"
    dest: "/var/lib/tomcat7/webapps/{{ opensrp_install_name }}.war"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"

- name: Restart the Tomcat7 Service
  become: yes
  become_user: root
  service:
    name: tomcat7
    state: restarted
