---
- name: Install MySQL client package
  become: yes
  become_user: "root"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-client
    - python-mysqldb

- name: Download MySQL CA certificate bundle
  become: yes
  become_user: root
  get_url:
    url: "{{ opensrp_mysql_ca_bundle_url }}"
    dest: "/usr/local/share/ca-certificates/mysql-ca-bundle.crt"
    force: yes
  register: downloaded_mysql_ca_bundle
  when: opensrp_mysql_ca_bundle_url|length > 0

- name: Update MySQL CA certificates
  become: yes
  become_user: root
  command: "update-ca-certificates"
  when: (opensrp_mysql_ca_bundle_url|length > 0 and downloaded_mysql_ca_bundle is changed)

- name: Create the OpenSRP MySQL databases
  mysql_db:
    login_host: "{{ opensrp_mysql_host }}"
    login_user: "{{ opensrp_mysql_root_user }}"
    login_password: "{{ opensrp_mysql_root_password }}"
    ca_cert: "/usr/local/share/ca-certificates/mysql-ca-bundle.crt"
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ opensrp_mysql_database }}"
    - "{{ opensrp_motech_database }}"

- name: Copy the Motech Quartz schema .sql file
  become: yes
  become_user: "root"
  copy:
    src: "tmp/opensrp_motech_database.sql"
    dest: "/tmp/{{ opensrp_motech_database }}.sql"
    owner: root
    group: root
    mode: 0600

- name: Dump the Motech Quarts schema .sql file
  become: yes
  become_user: "root"
  mysql_db:
    name: "{{ opensrp_motech_database }}"
    login_user: "{{ opensrp_mysql_root_user }}"
    login_password: "{{ opensrp_mysql_root_password }}"
    login_host: "{{ opensrp_mysql_host }}"
    state: import
    target: "/tmp/{{ opensrp_motech_database }}.sql"

- name: Create the OpenSRP MySQL user
  mysql_user:
    login_host: "{{ opensrp_mysql_host }}"
    login_user: "{{ opensrp_mysql_root_user }}"
    login_password: "{{ opensrp_mysql_root_password }}"
    name: "{{ opensrp_mysql_user }}"
    password: "{{ opensrp_mysql_password }}"
    host: "{{ opensrp_mysql_app_host }}"
    priv: "{{ opensrp_mysql_privilages_joiner.join(opensrp_mysql_databases) }}.*:{{ opensrp_mysql_user_privilages }}"
    state: present
