---
- name: Copy the OpenSRP migrations environment configs
  template:
    src: "templates/opensrp_local_checkout_path/configs/assets/migrations/environments/{{ item }}.properties.j2"
    dest: "{{ opensrp_local_checkout_path }}/configs/assets/migrations/environments/{{ item }}.properties"
  delegate_to: 127.0.0.1
  with_items:
    - "development"
  tags:
    - postgresql

- name: Copy psql migration scripts
  copy:
    src: "{{ opensrp_local_checkout_path }}/configs/assets/migrations"
    dest: "{{ opensrp_local_checkout_path }}/configs/assets"
  tags:
    - postgresql

- name: Install migration prerequisites
  become: yes
  become_user: "root"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip
    - python-migrate
    - postgresql
    - libpq-dev
    - python-psycopg2
  tags:
    - postgresql

- name: Make sure the OpenSRP PostgreSQL database exists
  postgresql_db:
    name: "{{ opensrp_postgresql_database }}"
    login_host: "{{ opensrp_postgres_host }}"
    login_user: "{{ opensrp_postgres_superuser }}"
    login_password: "{{ opensrp_postgres_superuser_password }}"
  tags:
    - postgresql

- name: Ensure OpenSRP psql user has the right access level
  postgresql_user:
    db: "{{ opensrp_postgresql_database }}"
    login_host: "{{ opensrp_postgres_host }}"
    login_user: "{{ opensrp_postgres_superuser }}"
    login_password: "{{ opensrp_postgres_superuser_password }}"
    name: "{{ opensrp_postgresql_user }}"
    password: "{{ opensrp_postgresql_password }}"
    encrypted: yes
    priv: ALL
    role_attr_flags: "{{ opensrp_postgresql_user_role_attr_flags }}"
  tags:
    - postgresql

- name: Make sure the Mybatis installation dir exists
  become: yes
  become_user: "root"
  file:
    path: "{{ opensrp_mybatis_install_dir }}"
    state: "directory"
    owner: "{{ ansible_ssh_user }}"
    mode: "0755"
  tags:
    - postgresql

- name: Download the Mybatis archive
  unarchive:
    src: "https://github.com/mybatis/migrations/releases/download/mybatis-migrations-{{ opensrp_mybatis_version }}/mybatis-migrations-{{ opensrp_mybatis_version }}-bundle.zip" # noqa 204
    dest: "{{ opensrp_mybatis_install_dir }}"
    remote_src: yes
  tags:
    - postgresql

- name: Run the Mybatis migrations # noqa 301
  command: "{{ opensrp_mybatis_install_dir }}/mybatis-migrations-{{ opensrp_mybatis_version }}/bin/migrate up --path={{ opensrp_local_checkout_path }}/configs/assets/migrations --env={{ opensrp_mybatis_env }} {{ opensrp_mybatis_migration_extra_args }}" # noqa 204
  tags:
    - postgresql

- name: Give opensrp user access to the database schemas
  postgresql_privs:
    db: "{{ opensrp_postgresql_database }}"
    login_host: "{{ opensrp_postgres_host }}"
    login_user: "{{ opensrp_postgres_superuser }}"
    login_password: "{{ opensrp_postgres_superuser_password }}"
    privs: ALL
    objs: "{{ item }}"
    type: schema
    roles: "{{ opensrp_postgresql_user }}"
    grant_option: no
  with_items:
    - core
    - error
    - schedule
    - feed
    - form
    - public
  tags:
    - postgresql

- name: Give opensrp user access to the database schemas
  postgresql_privs:
    db: "{{ opensrp_postgresql_database }}"
    login_host: "{{ opensrp_postgres_host }}"
    login_user: "{{ opensrp_postgres_superuser }}"
    login_password: "{{ opensrp_postgres_superuser_password }}"
    privs: ALL
    objs: ALL_IN_SCHEMA
    roles: "{{ opensrp_postgresql_user }}"
    grant_option: no
    schema: "{{ item }}"
  with_items:
    - core
    - error
    - schedule
    - feed
    - form
    - public
  tags:
    - postgresql

- name: Give opensrp user access to the database schemas
  postgresql_privs:
    db: "{{ opensrp_postgresql_database }}"
    login_host: "{{ opensrp_postgres_host }}"
    login_user: "{{ opensrp_postgres_superuser }}"
    login_password: "{{ opensrp_postgres_superuser_password }}"
    privs: USAGE
    type: sequence
    objs: ALL_IN_SCHEMA
    roles: "{{ opensrp_postgresql_user }}"
    grant_option: no
    schema: "{{ item }}"
  with_items:
    - core
    - error
    - schedule
    - feed
    - form
    - public
  tags:
    - postgresql
