---
- name: Ensure checkout directory is empty
  file:
    state: absent
    path: "{{ opensrp_local_checkout_path }}"
  tags:
    - postgresql

- name: Checking out codebase
  git:
    repo: "{{ opensrp_git_url }}"
    dest: "{{ opensrp_local_checkout_path }}"
    version: "{{ opensrp_version }}"
    recursive: yes
  tags:
    - postgresql

- name: Copy the OpenSRP migrations environment configs
  template:
    src: "templates/opensrp_local_checkout_path/configs/assets/migrations/environments/opensrp_mybatis_env.properties.j2"
    dest: "{{ opensrp_local_checkout_path }}/configs/assets/migrations/environments/{{ opensrp_mybatis_env }}.properties"
  tags:
    - postgresql

- name: Install migration prerequisites
  become: yes
  become_user: "root"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip
    - python-migrate
    - postgresql
    - libpq-dev
    - python-psycopg2
  tags:
    - postgresql

- name: Make sure the OpenSRP PostgreSQL database exists
  postgresql_db:
    name: "{{ opensrp_postgresql_database }}"
    login_host: "{{ opensrp_postgres_host }}"
    port: "{{ opensrp_postgres_port }}"
    login_user: "{{ opensrp_postgres_superuser }}"
    login_password: "{{ opensrp_postgres_superuser_password }}"
  tags:
    - postgresql

- name: Ensure OpenSRP psql user has the right access level
  postgresql_user:
    db: "{{ opensrp_postgresql_database }}"
    login_host: "{{ opensrp_postgres_host }}"
    port: "{{ opensrp_postgres_port }}"
    login_user: "{{ opensrp_postgres_superuser }}"
    login_password: "{{ opensrp_postgres_superuser_password }}"
    name: "{{ opensrp_postgresql_user }}"
    password: "{{ opensrp_postgresql_password }}"
    encrypted: yes
    priv: ALL
    role_attr_flags: "{{ opensrp_postgresql_user_role_attr_flags }}"
  tags:
    - postgresql

- name: Make sure the Mybatis installation dir exists
  become: yes
  become_user: "root"
  file:
    path: "{{ opensrp_mybatis_install_dir }}"
    state: "directory"
    owner: "{{ ansible_ssh_user }}"
    mode: "0755"
  tags:
    - postgresql

- name: Download the Mybatis archive
  unarchive:
    src: "https://github.com/mybatis/migrations/releases/download/mybatis-migrations-{{ opensrp_mybatis_version }}/mybatis-migrations-{{ opensrp_mybatis_version }}-bundle.zip" # noqa 204
    dest: "{{ opensrp_mybatis_install_dir }}"
    remote_src: yes
  tags:
    - postgresql

- name: Run the Mybatis migrations # noqa 301
  command: "{{ opensrp_mybatis_install_dir }}/mybatis-migrations-{{ opensrp_mybatis_version }}/bin/migrate up --path={{ opensrp_local_checkout_path }}/configs/assets/migrations --env={{ opensrp_mybatis_env }} {{ opensrp_mybatis_migration_extra_args }}" # noqa 204
  tags:
    - postgresql

- name: Ensure checkout directory is empty
  file:
    state: absent
    path: "{{ opensrp_local_checkout_path }}"
  tags:
    - postgresql
