---
- name: Copy the OpenSRP migrations environment configs
  template:
    src: "templates/opensrp_local_checkout_path/configs/assets/migrations/environments/{{ item }}.properties.j2"
    dest: "{{ opensrp_local_checkout_path }}/configs/assets/migrations/environments/{{ item }}.properties"
  delegate_to: 127.0.0.1
  with_items:
    - "development"
  tags:
    - psql-table-space

- name: Copy psql migration scripts
  copy:
    src: "{{ opensrp_local_checkout_path }}/configs/assets/migrations"
    dest: "{{ opensrp_local_checkout_path }}/configs/assets"
  tags:
    - psql-table-space

- name: Install migration prerequisites
  become: yes
  become_user: "root"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip
    - python-migrate
    - postgresql
    - libpq-dev
    - python-psycopg2
  tags:
    - psql-table-space


- name: Ensure OpenSRP psql user has the right access level
  postgresql_user:
    db: "{{ opensrp_postgresql_database }}"
    login_host: "{{ opensrp_postgres_host }}"
    login_user: "{{ opensrp_postgres_superuser }}"
    login_password: "{{ opensrp_postgres_superuser_password }}"
    name: "{{ opensrp_postgresql_user }}"
    password: "{{ opensrp_postgresql_password }}"
    encrypted: yes
    priv: ALL
    role_attr_flags: "{{ opensrp_postgresql_user_role_attr_flags }}"
  tags:
    - psql-table-space

- name: Make sure the Mybatis installation dir exists
  file:
    path: "{{ opensrp_mybatis_install_dir }}"
    state: "directory"
    mode: "0755"
  tags:
    - psql-table-space

- name: Download the Mybatis archive
  unarchive:
    src: "https://github.com/mybatis/migrations/releases/download/mybatis-migrations-{{ opensrp_mybatis_version }}/mybatis-migrations-{{ opensrp_mybatis_version }}-bundle.zip"
    dest: "{{ opensrp_mybatis_install_dir }}"
    remote_src: yes
  tags:
    - psql-table-space

- name: Run the Mybatis migrations # noqa 301
  command: "{{ opensrp_mybatis_install_dir }}/mybatis-migrations-{{ opensrp_mybatis_version }}/bin/migrate up --path={{ opensrp_local_checkout_path }}/configs/assets/migrations --env={{ opensrp_mybatis_env }} {{ opensrp_mybatis_migration_extra_args }}"
  tags:
    - psql-table-space
