---
- name: Copy the OpenSRP migrations environment configs
  template:
    src: "templates/opensrp_local_checkout_path/configs/assets/migrations/environments/{{ item }}.properties.j2"
    dest: "{{ opensrp_local_checkout_path }}/configs/assets/migrations/environments/{{ item }}.properties"
  delegate_to: 127.0.0.1
  with_items:
  - "development"
  tags:
  - psql-table-space

- name: Replace OpenSRP migrations scripts
  template:
    src: "templates/opensrp_local_checkout_path/configs/assets/migrations/{{ item }}.sh.j2"
    dest: "{{ opensrp_local_checkout_path }}/configs/assets/migrations/{{ item }}.sh"
  delegate_to: 127.0.0.1
  with_items:
  - "run_mybatis_migrations"
  tags:
  - psql-table-space

- name: Replace OpenSRP migrations shell scripts
  template:
    src: "templates/opensrp_local_checkout_path/configs/assets/migrations/{{ item }}.sh.j2"
    dest: "{{ opensrp_local_checkout_path }}/configs/assets/migrations/{{ item }}.sh"
  delegate_to: 127.0.0.1
  with_items:
  - "run_mybatis_migrations"
  tags:
  - psql-table-space

- name: Copy psql migration scripts
  copy:
    src: "{{ opensrp_local_checkout_path }}/configs/assets/migrations"
    dest: "{{ opensrp_local_checkout_path }}/configs/assets"
  tags:
  - psql-table-space

- name: Install migration prerequisites
  become: yes
  become_user: "root"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - unzip
  - python-migrate
  tags:
  - psql-table-space


- name: Ensure OpenSRP psql user has the right access level
  postgresql_user:
    login_host: "{{ opensrp_postgres_host }}"
    login_user: "{{ opensrp_postgres_superuser }}"
    login_password: "{{ opensrp_postgres_superuser_password }}"
    name: "{{ opensrp_postgres_user }}"
    password: "{{ opensrp_postgres_password }}"
    role_attr_flags: CREATEDB,NOSUPERUSER
  tags:
    - psql-table-space

- name: Execute migration script
  become: yes
  command: bash -lc "cd {{ opensrp_local_checkout_path }} && sh configs/assets/migrations/run_mybatis_migrations.sh {{ opensrp_install_postgres|lower }}"
  tags:
    - psql-table-space

