---
dhis_version: "2.26"
dhis_java_ops: "-Xmx2048m -Xms2048m"
dhis_java_packages:
  - openjdk-8-jre
dhis_java_home: "/usr/lib/jvm/java-8-openjdk-amd64"
dhis_user_home: "/home/{{ dhis_system_user }}"
dhis_system_user: dhis2
dhis_system_group: dhis2
dhis_certs_from_letsencrypt: True
dhis_site_name: "dhis.smartregister.org"

# Tomcat
dhis_tomcat_instance: "tomcat-dhis"
dhis_tomcat_http_port: 8082
dhis_tomcat_shutdown_port: 8007
dhis_tomcat_ajp_port: 8012
dhis_tomcat_https_port: 8443
dhis_tomcat_max_filesize: "52428800"
dhis_tomcat_fsize_threshold: "10485760"
dhis_tomcat_version: 7

# PostgreSQL
dhis_postgresql_user: dhis
dhis_postgresql_database: dhis2
dhis_postgresql_password: ""
dhis_postgresql_host: localhost
dhis_postgresql_port: 5432
dhis_postgresql_connection_url: "jdbc:postgresql://{{ dhis_postgresql_host }}:{{ dhis_postgresql_port }}/{{ dhis_postgresql_database }}"
dhis_postgresql_login_user: root
dhis_postgres_login_password:

# Certbot
dhis_certbot_create_certs: true
dhis_certbot_mail_address: ""
dhis_certbot_site_names:
  - "{{ dhis_site_name }}"

# Swap
dhis_swap_file_size_mb: 2048
dhis_swap_swappiness: 10
dhis_install_swap: false

# NGINX
dhis_nginx_proxy_read_timeout: "60s"
dhis_nginx_max_filesize: "50M"
dhis_nginx_ssl_cert: "fullchain.pem"
dhis_nginx_ssl_key: "privkey.pem"
dhis_nginx_ssl_src_dir: "/etc/letsencrypt/live/{{ dhis_site_name }}"
dhis_nginx_http_site_name: "{{ dhis_site_name }}-http"
dhis_nginx_https_site_name: "{{ dhis_site_name }}-https"
dhis_nginx_enabled_sites:
  - "{{ dhis_nginx_http_site_name }}"
  - "{{ dhis_nginx_https_site_name }}"
dhis_nginx_log_dir: "/var/log/nginx"
dhis_nginx_sites:
  - server:
      name: "{{ dhis_nginx_http_site_name }}"
      __listen: "80;\n  listen [::]:80;\n"
      server_name: "{{ dhis_site_name }}"
      return: "301 https://$server_name$request_uri"
      ssl:
        enabled: false
  - server:
      name: "{{ dhis_nginx_https_site_name }}"
      __listen: "443;\n  listen [::]:443;\n"
      server_name: "{{ dhis_site_name }}"
      client_max_body_size: "{{ dhis_nginx_max_filesize }}"
      ssl:
        enabled: true
        cert: "{{ dhis_nginx_ssl_cert }}"
        key: "{{ dhis_nginx_ssl_key }}"
        src_dir: "{{ dhis_nginx_ssl_src_dir }}"
        conf: "{{ dhis_site_name }}-ssl.conf"
        remote_src: "{{ dhis_certs_from_letsencrypt }}"
        create_symlink: "{{ dhis_certs_from_letsencrypt }}"
        access_log_format: "timed_combined"
      location1:
        name: /
        proxy_pass: "http://localhost:{{ dhis_tomcat_http_port }}"
        proxy_set_header:
        - Host $host
        - X-Real-IP $remote_addr
        - X-Forwarded-For $proxy_add_x_forwarded_for
        - X-Forwarded-Host $server_name
        - X-Forwarded-Proto https
        proxy_read_timeout: "{{ dhis_nginx_proxy_read_timeout }}"
        proxy_redirect: "off"
        proxy_next_upstream: "error timeout invalid_header http_500 http_502 http_503 http_504"
dhis_nginx_access_logs:
  - name: "timed_combined"
    format: "'$http_x_forwarded_for - $remote_user [$time_local]  \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" $request_time $upstream_response_time $gzip_ratio' $request_length"
    options: null
    filename: "access.log"

# Logstash
dhis_install_logstash: false
dhis_logstash_gelf_server: 127.0.0.1
dhis_logstash_gelf_port: "12204"
dhis_logstash_input_config_suffix: "{{ dhis_site_name }}"
dhis_clear_logstash_config: false
dhis_logstash_plugins:
  - name: logstash-output-gelf
    state: present
dhis_logstash_custom_outputs:
  - output: 'gelf'
    lines:
      - 'host => "{{ dhis_logstash_gelf_server }}"'
      - 'port => "{{ dhis_logstash_gelf_port }}"'
      - 'sender => "{{ dhis_site_name }}"'
dhis_logstash_custom_inputs:
  - input: 'file'
    lines:
      - 'path => ["{{ dhis_nginx_log_dir }}/{{ dhis_nginx_https_site_name }}-ssl-access.log"]'
      - 'start_position => "end"'
      - 'add_field => {'
      - '  ssl => true'
      - '  nginx_access => true'
      - '  from_nginx => true'
      - '  from_host => "%{host}"'
      - '  from_domain => "{{ dhis_site_name }}"'
      - '  from_{{ dhis_system_user }} => true'
      - '  git_version => "{{ dhis_version }}"'
      - '}'
